### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by juicenotbad** [IvanWoo22/SpliceSeq_Usage#1]
请教一下大佬，好像spliceseq的下载域名现在都打不开了，请问有没有什么解决办法？或者大佬有没有包呢？
以及，如果现在做类似的分析，有没有替代的方案？
感谢好心人！

**Comment by IvanWoo22** [comment]
查了一下，好像已经找不到java包了，我这边本地也没找到，还是看看其他替代工具吧，祝顺利！
